### ISSUE TITLE
Improve GH actions

### ISSUE THREAD

**Issue by leggerf** [Open-ForBC/OpenForBC-Benchmark#238]
There are a couple of things to fix:

- some checkout actions are outdated
- add another test-benchmarks.yml that runs weekly on devel. 

Example here:
```
name: Release Management
on: 
  schedule:
   - cron: "*/5 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: some-branch
```
